version: "3.8"

networks:
  esnet:

services:
  sysctl:
    image: alpine
    container_name: sysctl
    command: sh -c "sysctl -w vm.max_map_count=262144 && sleep 10"
    privileged: true
    network_mode: host
    restart: on-failure

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./data/es01/data/:/usr/share/elasticsearch/data
    networks:
      - esnet
    depends_on:
      - sysctl

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es02/data/:/usr/share/elasticsearch/data
    networks:
      - esnet
    depends_on:
      - sysctl
